"""added book author

Revision ID: 14698683aab9
Revises: 3237669d31fd
Create Date: 2021-07-25 19:35:25.382760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14698683aab9'
down_revision = '3237669d31fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books_author'))
    )
    op.create_table('books_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['books_author.id'], name=op.f('fk_books_book_author_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books_book'))
    )
    op.create_index(op.f('ix_books_book_author_id'), 'books_book', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_book_author_id'), table_name='books_book')
    op.drop_table('books_book')
    op.drop_table('books_author')
    # ### end Alembic commands ###
